// Generated by ts-to-zod
import { z } from "zod";
import type { Json } from "./../../types/database";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const addressesRowSchema = z.object({
  address_1: z.string(),
  address_2: z.string().nullable(),
  city: z.string(),
  country: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  state: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
  zip_code: z.string(),
});

export const addressesInsertSchema = z.object({
  address_1: z.string(),
  address_2: z.string().optional().nullable(),
  city: z.string(),
  country: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  state: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
  zip_code: z.string(),
});

export const addressesUpdateSchema = z.object({
  address_1: z.string().optional(),
  address_2: z.string().optional().nullable(),
  city: z.string().optional(),
  country: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  state: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
  zip_code: z.string().optional(),
});

export const addressesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("addresses_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const departmentRowSchema = z.object({
  created_at: z.string().nullable(),
  description: z.string(),
  id: z.string(),
  manager_id: z.string().nullable(),
  name: z.string(),
  organization_id: z.string(),
  updated_at: z.string().nullable(),
});

export const departmentInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string(),
  id: z.string().optional(),
  manager_id: z.string().optional().nullable(),
  name: z.string(),
  organization_id: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const departmentUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional(),
  id: z.string().optional(),
  manager_id: z.string().optional().nullable(),
  name: z.string().optional(),
  organization_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const departmentRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("department_manager_id_user_id_fk"),
    columns: z.tuple([z.literal("manager_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("department_organization_id_organization_id_fk"),
    columns: z.tuple([z.literal("organization_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organization"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const departmentMemberRowSchema = z.object({
  department_id: z.string(),
  user_id: z.string(),
});

export const departmentMemberInsertSchema = z.object({
  department_id: z.string(),
  user_id: z.string(),
});

export const departmentMemberUpdateSchema = z.object({
  department_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const departmentMemberRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "department_member_department_id_department_id_fk",
    ),
    columns: z.tuple([z.literal("department_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("department"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("department_member_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const emergencyContactsRowSchema = z.object({
  contact_email: z.string(),
  contact_name: z.string(),
  contact_number: z.string(),
  contact_relation: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const emergencyContactsInsertSchema = z.object({
  contact_email: z.string(),
  contact_name: z.string(),
  contact_number: z.string(),
  contact_relation: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const emergencyContactsUpdateSchema = z.object({
  contact_email: z.string().optional(),
  contact_name: z.string().optional(),
  contact_number: z.string().optional(),
  contact_relation: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const emergencyContactsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("emergency_contacts_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const notesRowSchema = z.object({
  content: jsonSchema,
  createdAt: z.string().nullable(),
  id: z.string(),
  title: z.string(),
  updatedAt: z.string().nullable(),
  user_id: z.string(),
});

export const notesInsertSchema = z.object({
  content: jsonSchema,
  createdAt: z.string().optional().nullable(),
  id: z.string().optional(),
  title: z.string(),
  updatedAt: z.string().optional().nullable(),
  user_id: z.string(),
});

export const notesUpdateSchema = z.object({
  content: jsonSchema.optional(),
  createdAt: z.string().optional().nullable(),
  id: z.string().optional(),
  title: z.string().optional(),
  updatedAt: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const notesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("notes_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const organizationRowSchema = z.object({
  address_1: z.string(),
  address_2: z.string().nullable(),
  city: z.string(),
  contact_email: z.string(),
  contact_name: z.string(),
  contact_number: z.string(),
  country: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  logo_url: z.string().nullable(),
  name: z.string(),
  payroll_pattern: z.string(),
  payroll_start_day: z.number(),
  state: z.string(),
  time_zone: z.string(),
  type: z.string(),
  updated_at: z.string().nullable(),
  website: z.string().nullable(),
  zip_code: z.string(),
});

export const organizationInsertSchema = z.object({
  address_1: z.string(),
  address_2: z.string().optional().nullable(),
  city: z.string(),
  contact_email: z.string(),
  contact_name: z.string(),
  contact_number: z.string(),
  country: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  logo_url: z.string().optional().nullable(),
  name: z.string(),
  payroll_pattern: z.string(),
  payroll_start_day: z.number(),
  state: z.string(),
  time_zone: z.string(),
  type: z.string(),
  updated_at: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
  zip_code: z.string(),
});

export const organizationUpdateSchema = z.object({
  address_1: z.string().optional(),
  address_2: z.string().optional().nullable(),
  city: z.string().optional(),
  contact_email: z.string().optional(),
  contact_name: z.string().optional(),
  contact_number: z.string().optional(),
  country: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  logo_url: z.string().optional().nullable(),
  name: z.string().optional(),
  payroll_pattern: z.string().optional(),
  payroll_start_day: z.number().optional(),
  state: z.string().optional(),
  time_zone: z.string().optional(),
  type: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
  zip_code: z.string().optional(),
});

export const organizationRelationshipsSchema = z.tuple([]);

export const organizationMembersRowSchema = z.object({
  organization_id: z.string(),
  user_id: z.string(),
});

export const organizationMembersInsertSchema = z.object({
  organization_id: z.string(),
  user_id: z.string(),
});

export const organizationMembersUpdateSchema = z.object({
  organization_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const organizationMembersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "organization_members_organization_id_organization_id_fk",
    ),
    columns: z.tuple([z.literal("organization_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organization"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("organization_members_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const organizationOwnersRowSchema = z.object({
  organization_id: z.string(),
  user_id: z.string(),
});

export const organizationOwnersInsertSchema = z.object({
  organization_id: z.string(),
  user_id: z.string(),
});

export const organizationOwnersUpdateSchema = z.object({
  organization_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const organizationOwnersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "organization_owners_organization_id_organization_id_fk",
    ),
    columns: z.tuple([z.literal("organization_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("organization"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("organization_owners_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const timeSheetRowSchema = z.object({
  clock_in: z.string(),
  clock_out: z.string().nullable(),
  created_at: z.string().nullable(),
  date: z.string(),
  id: z.string(),
  notes: z.string().nullable(),
  status: z.string(),
  total_worked_minutes: z.number().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const timeSheetInsertSchema = z.object({
  clock_in: z.string().optional(),
  clock_out: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  date: z.string(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  status: z.string().optional(),
  total_worked_minutes: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const timeSheetUpdateSchema = z.object({
  clock_in: z.string().optional(),
  clock_out: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  date: z.string().optional(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  status: z.string().optional(),
  total_worked_minutes: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const timeSheetRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("time_sheet_user_id_user_id_fk"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const timeSheetBreakRowSchema = z.object({
  break_end: z.string().nullable(),
  break_start: z.string(),
  id: z.string(),
  time_sheet_id: z.string(),
});

export const timeSheetBreakInsertSchema = z.object({
  break_end: z.string().optional().nullable(),
  break_start: z.string(),
  id: z.string().optional(),
  time_sheet_id: z.string(),
});

export const timeSheetBreakUpdateSchema = z.object({
  break_end: z.string().optional().nullable(),
  break_start: z.string().optional(),
  id: z.string().optional(),
  time_sheet_id: z.string().optional(),
});

export const timeSheetBreakRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal(
      "time_sheet_break_time_sheet_id_time_sheet_id_fk",
    ),
    columns: z.tuple([z.literal("time_sheet_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("time_sheet"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const userRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string().nullable(),
  date_of_birth: z.string().nullable(),
  email: z.string(),
  employment_status: z.string().nullable(),
  employment_type: z.string().nullable(),
  first_name: z.string(),
  gender: z.string().nullable(),
  hire_date: z.string().nullable(),
  id: z.string(),
  job_title: z.string().nullable(),
  last_name: z.string(),
  leave_date: z.string().nullable(),
  phone_number: z.string().nullable(),
  role: z.string().nullable(),
  salary_per_hour: z.number().nullable(),
  updated_at: z.string().nullable(),
  work_hours_per_week: z.number().nullable(),
  working_days_per_week: z.array(z.string()).nullable(),
});

export const userInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  date_of_birth: z.string().optional().nullable(),
  email: z.string(),
  employment_status: z.string().optional().nullable(),
  employment_type: z.string().optional().nullable(),
  first_name: z.string(),
  gender: z.string().optional().nullable(),
  hire_date: z.string().optional().nullable(),
  id: z.string(),
  job_title: z.string().optional().nullable(),
  last_name: z.string(),
  leave_date: z.string().optional().nullable(),
  phone_number: z.string().optional().nullable(),
  role: z.string().optional().nullable(),
  salary_per_hour: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  work_hours_per_week: z.number().optional().nullable(),
  working_days_per_week: z.array(z.string()).optional().nullable(),
});

export const userUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  date_of_birth: z.string().optional().nullable(),
  email: z.string().optional(),
  employment_status: z.string().optional().nullable(),
  employment_type: z.string().optional().nullable(),
  first_name: z.string().optional(),
  gender: z.string().optional().nullable(),
  hire_date: z.string().optional().nullable(),
  id: z.string().optional(),
  job_title: z.string().optional().nullable(),
  last_name: z.string().optional(),
  leave_date: z.string().optional().nullable(),
  phone_number: z.string().optional().nullable(),
  role: z.string().optional().nullable(),
  salary_per_hour: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  work_hours_per_week: z.number().optional().nullable(),
  working_days_per_week: z.array(z.string()).optional().nullable(),
});

export const userRelationshipsSchema = z.tuple([]);

export const employmentStatusSchema = z.union([
  z.literal("active"),
  z.literal("inactive"),
  z.literal("terminated"),
]);

export const employmentTypeSchema = z.union([
  z.literal("full_time"),
  z.literal("part_time"),
  z.literal("contract"),
  z.literal("internship"),
]);

export const organizationTypeSchema = z.union([
  z.literal("for-profit"),
  z.literal("non-profit"),
  z.literal("government"),
]);

export const payrollPatternSchema = z.union([
  z.literal("weekly"),
  z.literal("bi-weekly"),
  z.literal("monthly"),
]);

export const timeSheetStatusSchema = z.union([
  z.literal("pending"),
  z.literal("approved"),
  z.literal("rejected"),
  z.literal("clocked_in"),
  z.literal("clocked_out"),
]);

export const userRolesSchema = z.union([
  z.literal("admin"),
  z.literal("manager"),
  z.literal("staff"),
  z.literal("team_lead"),
]);

export const employeeInsertSchema = userInsertSchema
  .merge(addressesInsertSchema)
  .merge(emergencyContactsInsertSchema)
  .merge(departmentMemberInsertSchema)
  .merge(organizationMembersInsertSchema);
